# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build rae-dux mousekeyspr'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["rae_dux_left","rae_dux_right"]'
      custom_config: '["#define MIRYOKU_KLUDGE_MOUSEKEYSPR"]'
      kconfig: '["CONFIG_ZMK_MOUSE=y"]'
      branches: '[
        "zmkfirmware/zmk/main urob/zmk/tree/mouse-3.2",
      ]'
