# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku
name: 'Build Example tempest_dux nice_nano_v2 nice_view'
on:
  workflow_dispatch:
  push:
    branches: [tempest_dux]
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["tempest_dux_left nice_view_adapter nice_view","tempest_dux_right"]'
